baseURL = 'https://herd-ware.github.io'
languageCode = 'en-us'
theme = "relearn"
publishDir = "../docs"
defaultContentLanguage = "fr"

[params]
  themeVariant = [ "color-light", "color-dark" ]
  alwaysopen = false
  collapsibleMenu = true
  disableInlineCopyToClipBoard = true

[Languages]
[Languages.fr]
title = "HerdWare"
weight = 1
languageName = "Français"
[Languages.en]
title = "HerdWare"
weight = 2
languageName = "English"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
url = "https://github.com/herd-ware"
weight = 1
[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Publications"
url = "more/publi/"
weight = 2
[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-star'></i> À propos"
url = "more/about/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
url = "https://github.com/herd-ware"
weight = 1
[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Publications"
url = "more/publi/"
weight = 2
[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-star'></i> About"
url = "more/about/"
weight = 10

[markup.goldmark.renderer]
  unsafe = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]
